const Constants = {
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    LOGIN_NEXT_STEP: 'LOGIN_NEXT_STEP',
    LOGIN_PREV_STEP: 'LOGIN_PREV_STEP',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    LOGIN_RESET_ERRORS: 'LOGIN_RESET_ERRORS',

    REGISTRATION_FAILURE: 'REGISTRATION_FAILURE',
    REGISTRATION_RESET_ERRORS: 'REGISTRATION_RESET_ERRORS',
    REGISTRATION_NEXT_STEP: 'REGISTRATION_NEXT_STEP',
    REGISTRATION_PREV_STEP: 'REGISTRATION_PREV_STEP',

    SNIPPETS_RECEIVED: 'SNIPPETS_RECEIVED',
    SHARED_SNIPPETS_RECEIVED: 'SHARED_SNIPPETS_RECEIVED',
    ADD_SNIPPET: 'ADD_SNIPPET',
    DELETE_SNIPPET: 'DELETE_SNIPPET',
    SET_CURRENT_SNIPPET: 'SET_CURRENT_SNIPPET',
    SET_CURRENT_SNIPPET_PERMISSION: 'SET_CURRENT_SNIPPET_PERMISSION',


    SET_SHARE_INFO: 'SET_SHARE_INFO',


};

export default Constants;
